version: 1.21.{build}
os: Visual Studio 2015
environment:
  solution_path: PokemonSunMoonRNGTool.sln
pull_requests:
  do_not_increment_build_number: true
artifacts:
  - path: PokemonSunMoonRNGTool.zip
    name: PokemonSunMoonRNGTool
build:
  project: $(solution_path)
  verbosity: minimal
after_build:
  - ps: 7z a PokemonSunMoonRNGTool.zip .\PokemonSunMoonRNGTool\bin\Debug\PokemonSunMoonRNGTool.exe
